"""automigration

Revision ID: 067cd0ed8d73
Revises: 7585713649d7
Create Date: 2025-02-14 22:53:41.871033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '067cd0ed8d73'
down_revision = '7585713649d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hello', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.drop_column('hello')

    # ### end Alembic commands ###
