"""automigration

Revision ID: 226c2d6979ca
Revises: f7210d7bcd06
Create Date: 2025-02-14 23:13:19.240839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '226c2d6979ca'
down_revision = 'f7210d7bcd06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hello', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.drop_column('hello')

    # ### end Alembic commands ###
