"""automigration

Revision ID: 29b867c62408
Revises: ba8e4dcc13e4
Create Date: 2025-02-18 12:38:31.502015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29b867c62408'
down_revision = 'ba8e4dcc13e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mean_yearly_income', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.drop_column('mean_yearly_income')

    # ### end Alembic commands ###
