"""automigration

Revision ID: 362ba846f75e
Revises: ec62deb523af
Create Date: 2025-02-14 23:15:50.744514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '362ba846f75e'
down_revision = 'ec62deb523af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ji', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.drop_column('ji')

    # ### end Alembic commands ###
