"""automigration

Revision ID: 975c983cfae4
Revises: bfd88da98352
Create Date: 2025-02-14 21:37:17.792788

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '975c983cfae4'
down_revision = 'bfd88da98352'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('new_field', sa.String(length=255), nullable=False),
    sa.Column('company_type', sa.String(length=255), nullable=True),
    sa.Column('d-u-n-s_number', sa.Integer(), nullable=False),
    sa.Column('import_export', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('table1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table1',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('new_field', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('company_type', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('d-u-n-s_number', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('import_export', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('form')
    # ### end Alembic commands ###
