"""automigration

Revision ID: 9bf4a7b4fa83
Revises: 362ba846f75e
Create Date: 2025-02-14 23:17:37.106384

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9bf4a7b4fa83'
down_revision = '362ba846f75e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.drop_column('ji')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ji', mysql.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
