"""automigration

Revision ID: ba8e4dcc13e4
Revises: 112ab61846e7
Create Date: 2025-02-18 12:28:24.823240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba8e4dcc13e4'
down_revision = '112ab61846e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('new_field', sa.String(length=255), nullable=False),
    sa.Column('company_type', sa.String(length=255), nullable=True),
    sa.Column('d-u-n-s_number', sa.String(length=255), nullable=False),
    sa.Column('import_export', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', 'timestamp')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('form')
    # ### end Alembic commands ###
