"""automigration

Revision ID: ec62deb523af
Revises: 226c2d6979ca
Create Date: 2025-02-14 23:15:11.645226

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ec62deb523af'
down_revision = '226c2d6979ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.drop_column('hello')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hello', mysql.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
