"""automigration

Revision ID: f7210d7bcd06
Revises: 067cd0ed8d73
Create Date: 2025-02-14 23:12:58.625412

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f7210d7bcd06'
down_revision = '067cd0ed8d73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.drop_column('hello')
        batch_op.drop_column('next_field')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('next_field', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('hello', mysql.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
