        """
        form_data = {
            # General Information
            'applicant_name': request.form.get('applicant_name'),
            'title_function': request.form.get('title_function'), 
            'region': request.form.get('region'), 
            'county': request.form.get('county'),
            'city': request.form.get('city'),
            'state': request.form.get('state'),
            'email': request.form.get('email'),
            'website_address': request.form.get('website_address'),
            'business_phone': request.form.get('business_phone'),
            'business_address': request.form.get('business_address'),
            # Company Information
            'company_name': request.form.get('company_name'),
            'parent_company': request.form.get('parent_company'),
            'founder_ceo_name': request.form.get('founder_ceo_name'),
            'company_description': request.form.get('company_description'),
            'founded_established_year': request.form.get('founded_established_year'),
            'lifetime_sales_revenue': request.form.get('lifetime_sales_revenue'),
            'sector': request.form.get('sector'),
            'legal_structure': request.form.get('legal_structure'),
            'entity_type': request.form.get('entity_type'),
            'status': request.form.get('status'),
            'business_engagement_model': request.form.get('business_engagement_model'),
            'facility_type': request.form.get('facility_type'),
            'trade_type': request.form.get('trade_type'),
            'minority_owned': request.form.get('minority_owned'),
            'company_website': request.form.get('company_website'),
            'executive_contact_name': request.form.get('executive_contact_name'),
            'executive_contact_designation': request.form.get('executive_contact_designation'),
            'executive_contact_number': request.form.get('executive_contact_number'),
            'executive_contact_email': request.form.get('executive_contact_email'),
            'company_type': request.form.get('company_type'),
            'primary_markets': request.form.get('primary_markets'),
            # Industry Codes and Product Information    
            'major_industry_category': request.form.get('major_industry_category'),
            'major_industry_sub_category': request.form.get('major_industry_sub_category'),
            'duns_number': request.form.get('duns_number'),
            'napcs_number': request.form.get('napcs_number'),
            'naics_codes': request.form.get('naics_codes'),
            'sic_codes': request.form.get('sic_codes'),
            'ein_number': request.form.get('ein_number'),
            'company_certifications': request.form.get('company_certifications'),
            'company_equipment': request.form.get('company_equipment'),
            'property_owned_rented': request.form.get('property_owned_rented'),
            'property_size': request.form.get('property_size'),
            'manufacturing_materials': request.form.get('manufacturing_materials'),
            'esg_initiatives': request.form.get('esg_initiatives'),
            'global_primary_products_services': request.form.get('global_primary_products_services'),  
            'ny_state_primary_products_services': request.form.get('ny_state_primary_products_services'),
            # Workforce Size Information
            'global_employees': request.form.get('global_employees'),
            'us_employees': request.form.get('us_employees'),
            'ny_state_employees': request.form.get('ny_state_employees'),
            'ny_state_location_employees': request.form.get('ny_state_location_employees'),
            'executive_roles': request.form.get('executive_roles'),
            'leadership_roles': request.form.get('leadership_roles'),
            'professional_support_roles': request.form.get('professional_support_roles'),
            'engineering_roles': request.form.get('engineering_roles'),
            'technician_roles': request.form.get('technician_roles'),
            'other_roles': request.form.get('other_roles'),
            'percent_location_employees_semiconductor_mfg': request.form.get('percent_location_employees_semiconductor_mfg'),
            'workforce_projections_next_36months': request.form.get('workforce_projections_next_36months'),
            # Semiconductor Manufacturing Industry Suggestions
            'company_role_semiconductor_industry': request.form.get('company_role_semiconductor_industry'),
            'semiconductor_mfg_shortcomings': request.form.get('semiconductor_mfg_shortcomings'),
            'pivot_opportunities': request.form.get('pivot_opportunities'),
            'state_emphasis_suggestions': request.form.get('state_emphasis_suggestions')    
        }
        """
